### ISSUE TITLE
Defining yaml schema for the release notes

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2561]
* As a **data provider** of OpenTargets, I want **to have a clear specification on how the release should be formulated**.
* As a **member of the data team** I want to have a machine readable, standardised release note to easily establish data provenance.

## Background

An important requirement is to have a standardised versioning of the data provided by the experimental teams of OpenTargets. Such versioning is expected to propagated to the Partner Preview release of the Platform.

## Requirements

- [ ] Human and machine readable -> yaml file
- [ ] Consistent across OT projects. We need to involve the data providers to make sure all meadata is included that they think is important for the release.
- [ ] Robust process for extracting the sufficient information from the providers to make sure no data is released to OT without the sufficient metadata
- [ ] Consistent and robust way of generation of the file: sorting out who and how would generated the file. We can think about validation as well (there's a trade-off).

## Proposed format

The yaml format allows both machine and human readability, however manual editing of these file can easily lead to compromising the format.

```yaml
projectId: OTAR033
projectDescription: Keratinocytes
projectLead: Phil Jones
submittedBy: 
releaseDate: 2021-06-10
releaseVersion: v1.0
changes:
  - This time, a new dataset was released based on experiments on a new cell line.
  - Also, a previous dataset was updated as we have re-analysed the experimental data.
```
