### ISSUE TITLE
PIS is not collecting 'uniprot' and 'genenames' data

### ISSUE THREAD

**Issue by mbdebian** [opentargets/issues#2726]
**Describe the bug**
_uniprot_ and _genenames_ datasets are missing in PIS results.

**Observed behaviour**
When running a PIS session for all the steps, _target-inputs_ is missing _uniprot_ and _genenames_ datasets.

**Expected behaviour**
The _target-inputs_ section produced by PIS should contain _uniprot_ and _genenames_ datasets.

**To Reproduce**
Run PIS for step _target_

**Additional context**
This has happened on 13th September 2022 while preparing the 22.09 release input data.

**Comment by mbdebian** [comment]
'genenames' is now working, it looks like a networking problem while downloading the data from the EBI

**Comment by mbdebian** [comment]
Two new URLs have been tested for _UniProt_ data in _target_ step:
```yaml
- uri: https://rest.uniprot.org/uniprotkb/stream\?compressed\=true\&format\=txt\&query\=%28%28reviewed%3Atrue%29%29%20AND%20%28model_organism%3A9606%29
    output_filename: uniprot.txt.gz
    path: target-inputs/uniprot
  - uri: https://rest.uniprot.org/locations/stream?compressed=true&fields=id%2Cname%2Ccategory&format=tsv&query=%28%2A%29
    output_filename: uniprot-ssl.tsv.gz
    path: target-inputs/uniprot
```
These URLs work on the _Terminal_ using _wget_, but they still crash in PIS, raising a _Bad Request_ error.
