### ISSUE TITLE
Preparing datasets for the 22.11 platform release

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2792]
This ticket aims to collate all tasks of the data team required for the upcoming platform release.

- [ ] Fixing json schema for the release.

**Preparing evidence parsers repo:**
- [x] Updating configuration to make sure the most recent datasets are picked
- [ ] Creating new release.
- [x] Run evidence datasource parsers
- [x] Investigating resulting files to make sure new files indeed generated

**PPP**
- [x] [Updating](https://github.com/opentargets/PPP-evidence-configuration/blob/master/notebooks/Process%20ot_crispr%20configuration.ipynb) `ot_crispr` configuration to make sure we are picking up the new datasource.

**Post parsers**
- [ ] Call platform metrics 
- [ ] Investigate metrics to rule out silent issues.

**Comment by DSuveges** [comment]
As of Nov 7, we go no new crispr data, so no action is required in that space.

**Comment by DSuveges** [comment]
The following globals were used in the pipeline run:
```yaml
global:
  logDir: gs://otar000-evidence_input/parser_logs
  cacheDir: cache_dir
  schema: https://raw.githubusercontent.com/opentargets/json_schema/2.2.8.1
  EFOVersion: v3.47.0
```
