### ISSUE TITLE
Fix bug in Spark master URI configuration

### ISSUE THREAD

**Issue by tskir** [opentargets/issues#3145]
@d0choa @ireneisdoomed @DSuveges 

When experimenting with autoscaling (https://github.com/opentargets/issues/issues/3142), I noticed that enabling it seemingly didn't have any effect on performance. This is also something @d0choa observed and told me earlier this week.

Upon investigating further, it turns out the problem lies somewhere in Hydra configuration.

### Setting up the debugging

In `src/otg/common/session.py`, class `Session`, I added the following two lines to the beginning of `__init__`:

```python
print(f"Actual spark_uri = {spark_uri}")
raise SystemExit
```

This way, when I run any step, it will first print full Hydra configuration (as it always does), and then when initialising a Session object it will also output the actual `spark_uri` value it received.

### Expected behaviour

Each step has:

```
defaults:
    - session: dataproc
```

And in turn `dataproc.yaml` has:

```
spark_uri: yarn
```

So we can expect that the `spark_uri` will be set to `yarn`, which we need for autoscaling to work. 

### Observed behaviour
```
[...]
step:
  session:
    _target_: otg.common.session.Session
    app_name: otgenetics
    write_mode: overwrite
    spark_uri: yarn
    hail_home: /opt/conda/miniconda3/lib/python3.10/site-packages/hail
    start_hail: true
    extended_spark_conf: null
  _target_: otg.ld_index.LDIndexStep
[...]
Actual spark_uri = local[*]
```

While Hydra thinks that it is setting `spark_uri` to `yarn`, in reality at the time of initialising a Session object it is set to `local[*]`. No wonder, then, why the autoscaling doesn't work :upside_down_face:
