### ISSUE TITLE
Add biosample dependencies to PIS

### ISSUE THREAD

**Issue by Tobi1kenobi** [opentargets/issues#3478]
Downloading the relevant JSON files from Biosample ontologies (for now Uberon and Cell Ontology) for importing as a data source to generate a biosample index.
The cell ontology JSON can be found here: https://github.com/obophenotype/cell-ontology/releases/download/v2024-08-16/cl.json
The Uberon JSON can be found here: https://github.com/obophenotype/uberon/releases/download/v2024-09-03/uberon.json

However the above URLs should be modified so they always point to the latest release. Unsure how to do this myself.

**Comment by DSuveges** [comment]
Github has an API for requesting release specific data:
```bash
ORGANISATION="obophenotype"
REPO="cell-ontology"
URL="https://api.github.com/repos/${ORGANISATION}/${REPO}/releases/latest"

curl -s ${URL} | jq '.assets[] | select( .name == "cl.owl" ) | .browser_download_url'
```
Which gives you the download url: 
```
https://github.com/obophenotype/cell-ontology/releases/download/v2024-08-16/cl.owl
```
(Of course this can be done via Python or any other ways that can submit requests.)

**Comment by javfg** [comment]
Hi @Tobi1kenobi:

To retrieve these files, we only need to add two new tasks to PIS, in the config file. There's some more info [here](https://github.com/javfg/platform-input-support?tab=readme-ov-file#structure). We will need:

- The PIS Step where this should go, whether it is an existing step or a new one.
- The paths you want this to be saved in the input data bucket, which should depend on what you are later on doing with the files.

For this, you can take a look [here](https://github.com/javfg/platform-input-support/blob/master/config.yaml) to see the current steps, and their destinations. This might help you with figuring out where to put them.

For grabbing the latest versions, I think building the URLs like so is enough:
https://github.com/obophenotype/cell-ontology/releases/latest/download/cl.json
https://github.com/obophenotype/uberon/releases/latest/download/uberon.json

**Comment by DSuveges** [comment]
@javfg Does it mean, if these files only need to be downloaded, all we need to do is to add the following few lines to the config:
```yaml
biosamples:
  - name: download cl
    source: https://github.com/obophenotype/cell-ontology/releases/latest/download/cl.json
    destination: biosamples/cl.json
  - name: download uberon
    source: https://github.com/obophenotype/uberon/releases/latest/download/uberon.json
    destination: biosamples/uberon.json
```
