### ISSUE TITLE
Improve L2G model selectivity

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3610]
As a **developer** I want **to monitor the number of hits in every L2G iteration** because **it is an important indicator tof the model's selectivity**

## Background

The number of genes that receive a score above 0.5 for the same credible set is an interesting metric of the model's selectivity.
We observe a negative tendency in the last 3 iterations, the percentage of credible sets with a single prioritised gene has decreases, while the percentage with 2 or more has increased.
```
Freeze 4 (curated gold standards)
+----+------+-----+                                                             
|hits| count|    %|
+----+------+-----+
|   1|277894|76.32|
|   2| 65886| 18.1|
|  >2| 20327| 5.58|
+----+------+-----+

Iteration 5 (curated gold standards)
+----+------+-----+                                                             
|hits| count|    %|
+----+------+-----+
|   1|312521|74.69|
|   2| 78196|18.69|
|  >2| 27734| 6.63|
+----+------+-----+

Iteration 6 (gold standards based on L2G hits in production)
+----+------+-----+                                                             
|hits| count|    %|
+----+------+-----+
|   1|236372|68.97|
|   2| 80396|23.46|
|  >2| 25930| 7.57|
+----+------+-----+
```

This metric is not something that we monitor during training.

## Tasks

- [ ] Monitor this metric in future iterations
- [ ] How can we model the features so that the distinction between genes is clearer?
- [ ] Can we implement a strategy in the selection of positives/negatives in the gold standards to prioritise one over the other?

**Comment by ireneisdoomed** [comment]
# Analysis of credible sets with multiple prioritised genes (L2G >= 0.5)

I have prepared a dataset with cases where the assigned genes are more than 1, and I have prepared some quality metrics based on the availability of features. So that now I have a dataframe like this one: 
```
+--------------------------------+---------------+------------------+----------------------------------------------+
|studyLocusId                    |geneId         |score             |qualityControls                               |
+--------------------------------+---------------+------------------+----------------------------------------------+
|696aa17876038f0b46ac65c5e27d3fa7|ENSG00000075213|0.982434345980689 |[]                                            |
|696aa17876038f0b46ac65c5e27d3fa7|ENSG00000170381|0.7804732926950384|[VEP features missing, Coloc features missing]|
+--------------------------------+---------------+------------------+----------------------------------------------+
```

Looking at cases like this, it is clear why ENSG00000075213 is the top ranked gene. And it is clear as well that, regardless of the iterations we do on the VEP or Colocalisation features to finetune them, we are not going to improve the selectivity because we simply lack any functional genomics data for ENSG00000170381.

My question was to analyse systematically how many times we have this scenario.

## Take aways
- There are 106,326 unique affected credible sets (22%), where there is more than one gene with a score > 0.5
- Among those, in 75% of cases we prioritise 2 genes only, whereas we have more than 2 causal genes for 25,930 credible sets
- In 43% of cases, there is a significant (>= 0.15) score gap between the top and second-ranked genes.
- There is a significant amount of missing data, with over 50% of predictions having at least a feature group completely missing (VEP, Coloc, or Distance). As we know, this is a major limitation in our current model
- However, in ~34% of cases, the top-ranked gene has no quality control flags while the other genes do. This indicates that the model performs well when annotation for all feature groups is available

I think the most informative table is this one, where I try to understand the source of selectivity issues:
```
+-----------------------------------------------------------+--------------+------------------------------------------+
|flags                                                      |granular_count|general_flag                              |
+-----------------------------------------------------------+--------------+------------------------------------------+
|[First and incomplete VEP, Second and incomplete VEP]      |31002         |Both Incomplete - same group              |
|[Second and incomplete VEP, First and complete features]   |17318         |Only first complete                       |
|[Second and incomplete VEP, First and incomplete Coloc]    |15491         |Both Incomplete - different groups        |
|[Second and complete features, First and complete features]|14189         |Both Complete                             |
|[Second and incomplete Coloc, First and incomplete Coloc]  |7475          |Both Incomplete - same group              |
|[First and incomplete VEP, Second and complete features]   |5308          |Only second complete                      |
|[Second and incomplete Coloc, First and complete features] |4895          |Only first complete                       |
|[Second and incomplete Coloc, First and incomplete VEP]    |4597          |Both Incomplete - different groups        |
|[Second and complete features, First and incomplete Coloc] |3248          |Only second complete                      |
|[First and incomplete VEP]                                 |2764          |Genes have same score                     |
|[First and incomplete Coloc]                               |32            |Genes have same score                     |
|[First and complete features]                              |6             |Genes have same score                     |
|[First and incomplete Coloc, First and complete features]  |1             |Genes have same score - different features|
+-----------------------------------------------------------+--------------+------------------------------------------+
```

- The largest category, 31,002 cases, is where both the first and second ranked genes don't have VEP information. This means that at least they have Distance and Coloc annotation, which is **susceptible of improving**.
- The second largest category is `Only first complete`, with 22,213 credible sets, where changes in the feature modelling won't yield any benefits because simply there's no data. This is the case of the example highlighted above.
- It's also interesting the 14,189 cases where both genes are complete. Also another scenario where a **better modelling could improve the selectivity.**

It'd be good to reproduce this in future iterations. Code is here https://gist.github.com/ireneisdoomed/31086fe5ef8ddb76dd06d22c54950e2d

**Comment by ireneisdoomed** [comment]
These are the predictions with the feature matrix computed taking the max in the neighbourhood ([PR](https://github.com/opentargets/gentropy/pull/903)), and using the curation for model training

`gs://ot-team/irene/l2g/08112024/locus_to_gene_predictions`

Selectivity looks slightly better, with 99,541 credible sets with multiple genes
```
+----+------+                                                                   
|hits| count|
+----+------+
|  >2| 24192|
|   1|247555|
|   2| 75349|
+----+------+
```

**Comment by ireneisdoomed** [comment]
### SOA in the L2G Paper

From @addramir:
> 55.4% loci had a single gene with l2g>0.5
1.4% had >=2 genes with l2g>0.5
43.2% had 0 genes with l2g>0.5

**Comment by ireneisdoomed** [comment]
## 12/11_GSP_cs_selected_freez6_v5_nbh_ratio

Another set of predictions testing 2 things:
- _Less filtered and much bigger gold standard_: Based on old L2G hits, here credible sets are picked up based on distance, and not based on the availability of functional genomics data. 
```
+---------------+------+                                                        
|goldStandardSet| count|
+---------------+------+
|       positive| 15863|
|       negative|332719|
+---------------+------+
```
Path: `gs://genetics-portal-dev-analysis/yt4/20241024_EGL_playground/GSP_cs_selected_freez6_v5.parquet`

- Redefinition of the neihbourhood features to match the old L2G. For every credible set, instead of substracting the max in the region, we divide them.
Path: `gs://ot-team/irene/l2g/12112024/feature_matrix`


Predictions are really unselective, we have flipped the coin.
```
+----+------+                                                                   
|hits| count|
+----+------+
|  >2|453793|
|   1|  7812|
|   2| 10113|
+----+------+
```

IMO we are observing a huge overfitting here. I think it'd be a very good idea to plot a learning curve to decide training set size and to diagnose how fit is the model.

**Comment by ireneisdoomed** [comment]
## locus_to_gene_egl_stringent

This model was trained by @@xyg123 based on a selected list of Effector gene pairs.
Model used is here `opentargets/locus_to_gene_egl_stringent`

Strikingly, the selectivity is exactly the same as the previous results based on a very different gold standard.
```
+----+------+                                                                   
|hits| count|
+----+------+
|  >2|453793|
|   1|  7812|
|   2| 10113|
+----+------+
```

The commonality between 2 runs is the feature matrix, I'm going to train the model with a previous GS to see if the new neighbourhood features are the culprit.

This is the config for these predictions:
```
step: locus_to_gene
      step.run_mode: predict
      step.predictions_path: gs://genetics-portal-dev-analysis/xg1/Chembl_l2g_goldstandards/Predictions/EGL_predictions_2410_freeze6_stringent
      step.feature_matrix_path: gs://ot-team/irene/l2g/12112024/feature_matrix
      step.credible_set_path: gs://ot_orchestration/releases/24.10_freeze6/credible_set
      step.hf_hub_repo_id: opentargets/locus_to_gene_egl_stringent
      step.session.spark_uri: yarn
```

**Comment by addramir** [comment]
It looks one to one the same. Very suspicious. Also, did you filter by protein coding genes only?

**Comment by ireneisdoomed** [comment]
## 12/11_curation_1211_fm

Following up from my previous comment, and to check whether the problem was coming from the changes in the nbh features, I've rerun the model with the ETL curation and the 12/11 feature matrix. Results look good this time:
```
# This is all genes
+----+------+                                                                   
|hits| count|
+----+------+
|  >2| 23024|
|   1|250890|
|   2| 81803|
+----+------+
```

@addramir In fact, these features seem to perform slightly better than the previous approach where nbh features were substracted and not divided.

Again, my hypothesis is that @xyg123 model must have a big overfitting problem.

```
# config
  - id: l2g_train
    # prerequisites:
    #   - l2g_feature_matrix
    params:
      step: locus_to_gene
      step.run_mode: train
      step.wandb_run_name: 12/11_curation_1211_fm
      step.hf_hub_repo_id: opentargets/locus_to_gene
      step.hf_model_commit_message: "chore: model trained with 12/11 fm and curation gs"
      step.model_path: gs://ot-team/irene/l2g/12112024-etl/locus_to_gene_model/classifier.skops
      step.credible_set_path: gs://ot_orchestration/releases/24.10_freeze6/credible_set
      step.variant_index_path: gs://ot_orchestration/releases/24.10_freeze6/variant_index
      step.feature_matrix_path: gs://ot-team/irene/l2g/12112024/feature_matrix
      step.gold_standard_curation_path: gs://genetics_etl_python_playground/input/l2g/gold_standard/curation.json
      step.gene_interactions_path: gs://genetics_etl_python_playground/static_assets/interaction # OTP 23.12 data
      step.hyperparameters.n_estimators: 100
      step.hyperparameters.max_depth: 5
      step.hyperparameters.loss: log_loss
      +step.session.extended_spark_conf: "{spark.kryoserializer.buffer.max:500m, spark.sql.autoBroadcastJoinThreshold:'-1'}"
    # prerequisites:
    #   - l2g_feature_matrix
  - id: l2g_predict
    prerequisites:
      - l2g_train
    params:
      step: locus_to_gene
      step.run_mode: predict
      step.predictions_path: gs://ot-team/irene/l2g/12112024-etl/locus_to_gene_predictions
      step.feature_matrix_path: gs://ot-team/irene/l2g/12112024/feature_matrix
      step.credible_set_path: gs://ot_orchestration/releases/24.10_freeze6/credible_set
      step.hf_hub_repo_id: opentargets/locus_to_gene
      step.session.spark_uri: yarn
    prerequisites:
      - l2g_train
```
